#pragma once

#include <cstdint>
#include <fmt/format.h>
#include <quark/utils/diagnostic.hpp>
#include <source_location>
#include <string_view>
#include <vulkan/vulkan_core.h>

namespace quark::vk {

// NOLINTNEXTLINE(readability-function-size)
[[nodiscard]] constexpr std::string_view vk_result_name(VkResult r) noexcept {
  switch (r) {
  case VK_SUCCESS:
    return "VK_SUCCESS";
  case VK_NOT_READY:
    return "VK_NOT_READY";
  case VK_TIMEOUT:
    return "VK_TIMEOUT";
  case VK_EVENT_SET:
    return "VK_EVENT_SET";
  case VK_EVENT_RESET:
    return "VK_EVENT_RESET";
  case VK_INCOMPLETE:
    return "VK_INCOMPLETE";

  case VK_ERROR_OUT_OF_HOST_MEMORY:
    return "VK_ERROR_OUT_OF_HOST_MEMORY";
  case VK_ERROR_OUT_OF_DEVICE_MEMORY:
    return "VK_ERROR_OUT_OF_DEVICE_MEMORY";
  case VK_ERROR_INITIALIZATION_FAILED:
    return "VK_ERROR_INITIALIZATION_FAILED";
  case VK_ERROR_DEVICE_LOST:
    return "VK_ERROR_DEVICE_LOST";
  case VK_ERROR_MEMORY_MAP_FAILED:
    return "VK_ERROR_MEMORY_MAP_FAILED";
  case VK_ERROR_LAYER_NOT_PRESENT:
    return "VK_ERROR_LAYER_NOT_PRESENT";
  case VK_ERROR_EXTENSION_NOT_PRESENT:
    return "VK_ERROR_EXTENSION_NOT_PRESENT";
  case VK_ERROR_FEATURE_NOT_PRESENT:
    return "VK_ERROR_FEATURE_NOT_PRESENT";
  case VK_ERROR_INCOMPATIBLE_DRIVER:
    return "VK_ERROR_INCOMPATIBLE_DRIVER";
  case VK_ERROR_TOO_MANY_OBJECTS:
    return "VK_ERROR_TOO_MANY_OBJECTS";
  case VK_ERROR_FORMAT_NOT_SUPPORTED:
    return "VK_ERROR_FORMAT_NOT_SUPPORTED";
  case VK_ERROR_FRAGMENTED_POOL:
    return "VK_ERROR_FRAGMENTED_POOL";
  case VK_ERROR_UNKNOWN:
    return "VK_ERROR_UNKNOWN";

  // VK_VERSION_1_0
  case VK_ERROR_VALIDATION_FAILED:
    return "VK_ERROR_VALIDATION_FAILED";

    // VK_VERSION_1_1
#ifdef VK_VERSION_1_1
  case VK_ERROR_OUT_OF_POOL_MEMORY:
    return "VK_ERROR_OUT_OF_POOL_MEMORY";
  case VK_ERROR_INVALID_EXTERNAL_HANDLE:
    return "VK_ERROR_INVALID_EXTERNAL_HANDLE";
#endif

    // VK_VERSION_1_2
#ifdef VK_VERSION_1_2
  case VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS:
    return "VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS";
  case VK_ERROR_FRAGMENTATION:
    return "VK_ERROR_FRAGMENTATION";
#endif

    // VK_VERSION_1_3
#ifdef VK_VERSION_1_3
  case VK_PIPELINE_COMPILE_REQUIRED:
    return "VK_PIPELINE_COMPILE_REQUIRED";
#endif

    // VK_VERSION_1_4
#ifdef VK_VERSION_1_4
  case VK_ERROR_NOT_PERMITTED:
    return "VK_ERROR_NOT_PERMITTED";
#endif

    // VK_KHR_surface
#ifdef VK_ERROR_SURFACE_LOST_KHR
  case VK_ERROR_SURFACE_LOST_KHR:
    return "VK_ERROR_SURFACE_LOST_KHR";
#endif
#ifdef VK_ERROR_NATIVE_WINDOW_IN_USE_KHR
  case VK_ERROR_NATIVE_WINDOW_IN_USE_KHR:
    return "VK_ERROR_NATIVE_WINDOW_IN_USE_KHR";
#endif

    // VK_KHR_swapchain
#ifdef VK_SUBOPTIMAL_KHR
  case VK_SUBOPTIMAL_KHR:
    return "VK_SUBOPTIMAL_KHR";
#endif
#ifdef VK_ERROR_OUT_OF_DATE_KHR
  case VK_ERROR_OUT_OF_DATE_KHR:
    return "VK_ERROR_OUT_OF_DATE_KHR";
#endif

    // VK_KHR_display_swapchain
#ifdef VK_ERROR_INCOMPATIBLE_DISPLAY_KHR
  case VK_ERROR_INCOMPATIBLE_DISPLAY_KHR:
    return "VK_ERROR_INCOMPATIBLE_DISPLAY_KHR";
#endif

    // VK_NV_glsl_shader
#ifdef VK_ERROR_INVALID_SHADER_NV
  case VK_ERROR_INVALID_SHADER_NV:
    return "VK_ERROR_INVALID_SHADER_NV";
#endif

    // VK_KHR_video_queue
#ifdef VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR
  case VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR:
    return "VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR";
#endif
#ifdef VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR
  case VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR:
    return "VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR";
#endif
#ifdef VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR
  case VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR:
    return "VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR";
#endif
#ifdef VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR
  case VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR:
    return "VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR";
#endif
#ifdef VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR
  case VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR:
    return "VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR";
#endif
#ifdef VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR
  case VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR:
    return "VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR";
#endif

    // VK_EXT_image_drm_format_modifier
#ifdef VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT
  case VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT:
    return "VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT";
#endif

    // VK_EXT_present_timing
#ifdef VK_ERROR_PRESENT_TIMING_QUEUE_FULL_EXT
  case VK_ERROR_PRESENT_TIMING_QUEUE_FULL_EXT:
    return "VK_ERROR_PRESENT_TIMING_QUEUE_FULL_EXT";
#endif

    // VK_EXT_full_screen_exclusive
#ifdef VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT
  case VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT:
    return "VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT";
#endif

    // VK_KHR_deferred_host_operations
#ifdef VK_THREAD_IDLE_KHR
  case VK_THREAD_IDLE_KHR:
    return "VK_THREAD_IDLE_KHR";
#endif
#ifdef VK_THREAD_DONE_KHR
  case VK_THREAD_DONE_KHR:
    return "VK_THREAD_DONE_KHR";
#endif
#ifdef VK_OPERATION_DEFERRED_KHR
  case VK_OPERATION_DEFERRED_KHR:
    return "VK_OPERATION_DEFERRED_KHR";
#endif
#ifdef VK_OPERATION_NOT_DEFERRED_KHR
  case VK_OPERATION_NOT_DEFERRED_KHR:
    return "VK_OPERATION_NOT_DEFERRED_KHR";
#endif

    // VK_KHR_video_encode_queue
#ifdef VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR
  case VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR:
    return "VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR";
#endif

    // VK_EXT_image_compression_control
#ifdef VK_ERROR_COMPRESSION_EXHAUSTED_EXT
  case VK_ERROR_COMPRESSION_EXHAUSTED_EXT:
    return "VK_ERROR_COMPRESSION_EXHAUSTED_EXT";
#endif

    // VK_EXT_shader_object
#ifdef VK_INCOMPATIBLE_SHADER_BINARY_EXT
  case VK_INCOMPATIBLE_SHADER_BINARY_EXT:
    return "VK_INCOMPATIBLE_SHADER_BINARY_EXT";
#endif
#ifdef VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT
  case VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT:
    return "VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT";
#endif

    // VK_KHR_pipeline_binary
#ifdef VK_PIPELINE_BINARY_MISSING_KHR
  case VK_PIPELINE_BINARY_MISSING_KHR:
    return "VK_PIPELINE_BINARY_MISSING_KHR";
#endif
#ifdef VK_ERROR_NOT_ENOUGH_SPACE_KHR
  case VK_ERROR_NOT_ENOUGH_SPACE_KHR:
    return "VK_ERROR_NOT_ENOUGH_SPACE_KHR";
#endif

    // Aliases you listed
#ifdef VK_ERROR_VALIDATION_FAILED_EXT
  case VK_ERROR_VALIDATION_FAILED_EXT:
    return "VK_ERROR_VALIDATION_FAILED_EXT";
#endif
#ifdef VK_ERROR_OUT_OF_POOL_MEMORY_KHR
  case VK_ERROR_OUT_OF_POOL_MEMORY_KHR:
    return "VK_ERROR_OUT_OF_POOL_MEMORY_KHR";
#endif
#ifdef VK_ERROR_INVALID_EXTERNAL_HANDLE_KHR
  case VK_ERROR_INVALID_EXTERNAL_HANDLE_KHR:
    return "VK_ERROR_INVALID_EXTERNAL_HANDLE_KHR";
#endif
#ifdef VK_ERROR_FRAGMENTATION_EXT
  case VK_ERROR_FRAGMENTATION_EXT:
    return "VK_ERROR_FRAGMENTATION_EXT";
#endif
#ifdef VK_ERROR_NOT_PERMITTED_EXT
  case VK_ERROR_NOT_PERMITTED_EXT:
    return "VK_ERROR_NOT_PERMITTED_EXT";
#endif
#ifdef VK_ERROR_NOT_PERMITTED_KHR
  case VK_ERROR_NOT_PERMITTED_KHR:
    return "VK_ERROR_NOT_PERMITTED_KHR";
#endif
#ifdef VK_ERROR_INVALID_DEVICE_ADDRESS_EXT
  case VK_ERROR_INVALID_DEVICE_ADDRESS_EXT:
    return "VK_ERROR_INVALID_DEVICE_ADDRESS_EXT";
#endif
#ifdef VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS_KHR
  case VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS_KHR:
    return "VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS_KHR";
#endif
#ifdef VK_PIPELINE_COMPILE_REQUIRED_EXT
  case VK_PIPELINE_COMPILE_REQUIRED_EXT:
    return "VK_PIPELINE_COMPILE_REQUIRED_EXT";
#endif
#ifdef VK_ERROR_PIPELINE_COMPILE_REQUIRED_EXT
  case VK_ERROR_PIPELINE_COMPILE_REQUIRED_EXT:
    return "VK_ERROR_PIPELINE_COMPILE_REQUIRED_EXT";
#endif

  default:
    return "VK_RESULT_UNKNOWN";
  }
}

[[nodiscard]] inline util::Error
vk_error(VkResult r, std::string_view what,
         std::source_location loc = std::source_location::current()) {
  util::Error e = util::details::make_error(
      util::Errc::ApiError, util::Severity::Error,
      /*module=*/"vk", loc, "{} failed: {} ({})", what, vk_result_name(r),
      static_cast<std::int32_t>(r));

  e.domain = static_cast<std::int32_t>(r);
  return e;
}

} // namespace quark::vk
