option(QUARK_ENABLE_ASAN "Enable AddressSanitizer" OFF)
option(QUARK_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(QUARK_ENABLE_TSAN "Enable ThreadSanitizer" OFF)
option(QUARK_ENABLE_LTO "Enable Link Time Optimization" OFF)

function(quark_apply_sanitizers target)
  if(MSVC)
    return()
  endif()

  if(QUARK_ENABLE_TSAN)
    target_compile_options(${target} PRIVATE -fsanitize=thread -fno-omit-frame-pointer -g)
    target_link_options(${target} PRIVATE -fsanitize=thread)
  else()
    if(QUARK_ENABLE_ASAN)
      target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer -g)
      target_link_options(${target} PRIVATE -fsanitize=address)
    endif()

    if(QUARK_ENABLE_UBSAN)
      target_compile_options(${target} PRIVATE -fsanitize=undefined -fno-omit-frame-pointer -g)
      target_link_options(${target} PRIVATE -fsanitize=undefined)
    endif()

    if(QUARK_ENABLE_UBSAN)
      target_compile_options(${target} PRIVATE -fno-sanitize-recover=undefined)
    endif()
  endif()
endfunction()

function(quark_apply_lto target)
  if(NOT QUARK_ENABLE_LTO)
    return()
  endif()

  include(CheckIPOSupported)
  check_ipo_supported(RESULT ipo_ok OUTPUT ipo_err)
  if(ipo_ok)
    set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
  else()
    message(WARNING "IPO/LTO not supported: ${ipo_err}")
  endif()
endfunction()
